### ISSUE TITLE
Queue stops processing

### ISSUE THREAD

**Issue by tasgray** [ep1cman/unifi-protect-backup#115]
* Unifi Protect Backup version: 0.10.1
* Unifi Protect version: 2.9.33
* Python version: Unsure
* Operating System: Unsure
* Are you using a docker container or native?: Container

### Description

I have the container running and it works perfectly when it first starts. All clips are downloaded. Once it completes the queue, it seems to continue adding events to the queue however it doesn't seem to continue downloading any of the new events. If I restart the container it downloads them all, but then it repeats the same behaviour. I wonder if I'm missing something obvious, or this is intended behaviour?

### What I Did

Environment Variables 
![image](https://github.com/ep1cman/unifi-protect-backup/assets/5292389/1ba69e86-255f-4098-8a0b-704e7c63822f)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Swallowtail23** [comment]
Likely same that I'm seeing at end of https://github.com/ep1cman/unifi-protect-backup/issues/113 (see last comments).
For now I'm restarting the container every 15 mins

**Comment by ep1cman** [comment]
Sadly this application functions via undocumented APIs and sometimes unifi make changes that break things. That seems to be the case in protect version [`2.9.33`](https://community.ui.com/releases/UniFi-Protect-Application-2-9-33/1c1949d2-0c84-49f0-a880-14335d44878e). So much so that they have now actively remove this release from the general release channel.

At this time all I can recommend is not updating to this new firmware (don't use early access updates from unifi either, theyre not worth the trouble and often very buggy). Rather than try fix what might well be a bug in Unifi protect, I will monitor the releases and if this issue persists once a new stable release is out I will look into fixing the bug.

**Comment by ep1cman** [comment]
Hi @tasgray, could you please update to the latest unifi protect release that was released yesterday and the latest release of this tool that I just pushed.

Please let me know if you still encounter this bug, if I don't hear back I will mark this as closed in a couple weeks

Thanks
