### ISSUE TITLE
Backup past and missed clips manually?

### ISSUE THREAD

**Issue by florianmueller** [ep1cman/unifi-protect-backup#53]
Is there a way to run the script manually to backup all past video clips that have not been backuped yet?

Use case:
- Inital installation of this tool, and backing up everything that is already on protect
- or, the docker/script failed for some reason over a time period, and now you have non-backuped footage that you would like to backup as well between the day when the script stopped and when you discovered it and restarted the task.

Thank you, that would be great! Otherwise, great work and tool! Thank you!

**Comment by ep1cman** [comment]
As it stands, no this tool cannot do that. It currently isnt really setup to that robust, it just makes a best effort attempt. #49 already lays out some of what youve mentioned. Sadly my free time is somewhat lacking at the moment due to getting a puppy, but this is something I plan on improving in the future.

You can use the following tool to do a full backup of the existing videos: https://github.com/danielfernau/unifi-protect-video-downloader

**Comment by florianmueller** [comment]
Thanks a lot, that tool was a great suggestion, got my footage in no time :)
No worries, great job on the current status of the tool, saves my footage perfectly to Dropbox on any event.

**Comment by ep1cman** [comment]
Hi,

Thank you for your patience. This feature is now implemented in the latest update. The tool now ensures all events within the retention window are backed up, even if they occurred before it was first run.
