### ISSUE TITLE
Feature Request: Ability to execute current events and then quit

### ISSUE THREAD

**Issue by paulhaigh** [ep1cman/unifi-protect-backup#74]
### Description
Rather than the code running and re-polling every 5 mins, can we have an option for it to check the current queue, process all items and then quit?

This would allow me to vary the schedule of polling by using cron to manage my poll frequency rather than using the backed-in 5 min polling frequency.

I'd rather the code executed the entire queue and then terminated, rather than keep on polling.

**Comment by paulhaigh** [comment]
From the log I saw this:

`2023-01-13 13:51:34 [   DEBUG   ] unifi_protect_backup.uploader              : [63c161c900451403870fd5fe]  Uploaded
2023-01-13 13:52:41 [   DEBUG   ] unifi_protect_backup.missing_event_checker :   Total undownloaded events: 0
2023-01-13 13:52:41 [   DEBUG   ] unifi_protect_backup.missing_event_checker :   Undownloaded events of wanted types: 0
2023-01-13 13:57:42 [   DEBUG   ] unifi_protect_backup.missing_event_checker :   Total undownloaded events: 0
2023-01-13 13:57:42 [   DEBUG   ] unifi_protect_backup.missing_event_checker :   Undownloaded events of wanted types: 0`

so assuming that it's polling every 5 mins for new events, but reading the code (I'm no python person), it seems like it might be not doing that when a new event happens, so I could be misreading the logic here.

**Comment by ep1cman** [comment]
The way the application works is as follows:

- when it starts it compares its database with all the events stored on the UniFi protect instance. If there are any within the retention period set that are not in the database those are considered "missing" and immediately added to the queue
- from this point onward the tool connects to a websocket published by UniFi protect which will notify the tool of new events when they occur and it then download them.
- once every 5 minutes the check for missing events re-occurs in order to check if any events were missed (e.g there was an interrupt in the network or the tool was stopped for some time)

**Comment by paulhaigh** [comment]
Does the purge happen also on that 5 min timer for old events?

**Comment by ep1cman** [comment]
The purge happens on launch and then every 24 hours, but the interval is configurable with a command line option
